// lib/model/habit.dart
import 'package:hive/hive.dart';

part 'habit.g.dart'; // This file will be generated by build_runner

@HiveType(typeId: 0)
class Habit extends HiveObject {
  @HiveField(0)
  String title;

  @HiveField(1)
  final DateTime creationDate;

  @HiveField(2)
  final List<DateTime> completedDates;

  Habit({
    required this.title,
    required this.creationDate,
    List<DateTime>? completedDates,
  }) : this.completedDates = completedDates ?? [];
}